### ISSUE TITLE
请问地图上方的信息流 都流向了广东 我可以修改流动目标到其他省份吗 ？

### ISSUE THREAD

**Issue by KyonCN** [jyolo/wLogger#10]
还有一个nginx 路径反代的问题 

   location /abc {
        proxy_pass http://localhost:8899/;
       root /path/to/wLogger/webServer;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        }

我用这段代码反向代理 所有静态资源都无法正确加载  只能打开页面

还望大佬赐教 谢谢！

**Comment by KyonCN** [comment]
还有提个建议 大佬可以把nginx的推荐日志格式写入README 因为确实有很多格式不兼容  有的格式兼容 但会少数据 我在这上面疯狂踩坑  囧

**Comment by jyolo** [comment]
server
{
    listen 80;

    server_name local.logger.com;

	
	location /
        {
            proxy_pass http://127.0.0.1:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            
            add_header X-Cache $upstream_cache_status;
            
  
            
    	    add_header Cache-Control no-cache;
             expires 12h;
        }

    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    

    access_log  /www/wwwlogs/local.logger.com.log;
    error_log  /www/wwwlogs/local.logger.com.error.log;
}

试试 这个配置 ； 我线上的格式 ：

log_format custom '$remote_addr $http_x_forwarded_for $scheme "$request" [$request_body] $request_length $request_time $upstream_response_time $status $body_bytes_sent $bytes_sent $connection $connection_requests $http_referer "$http_user_agent" "$time_local" "$upstream_addr"';

每个变量什么意思 可以自己去看看官方手册！

**Comment by jyolo** [comment]
![image](https://user-images.githubusercontent.com/9959996/105014417-606a7980-5a7b-11eb-8d5c-dffc5eddd118.png)
地图中流量轨迹汇聚点，自己定义geo坐标点就行。里面有geo.js，改成你自己的所在地就行了

**Comment by jyolo** [comment]
感谢反馈！

**Comment by KyonCN** [comment]
感谢
