### ISSUE TITLE
已使用三年，反馈几个小问题

### ISSUE THREAD

**Issue by beiguancyc** [jyolo/wLogger#15]
我一直在Windows下使用，将三部分分别注册为inputer outputer web三个服务， 环境为nginx+mongodb，三年来非常稳定，但是有几个问题
1.mongodb有时会占用CPU100%，重启也不能解决，但是只要将outputer服务重启一下问题立刻解决，因为此问题触发几率极低，未能找到原因。

2.近期才发生的问题，我现在的文件存储在mongodb的GridFS Buckets中，通过nginx对外访问。但是现在要访问文件速度非常非常的慢，经常访问失败， 刷新很多次以后才能成功。
前几天偶然把web服务关掉，访问速度立即恢复。然后我又做了多次试验，确定只要关掉web就能保证GridFS的访问速度。
而如果web开着，只有GridFS的访问速度会受影响，数据不受影响。

不知道其他使用者有没有碰到以上问题

**Comment by Tmx8911** [comment]
我想请教一下ubuntu+apache怎么搭建啊，与遇到些问题

**Comment by beiguancyc** [comment]
> 我想请教一下ubuntu+apache怎么搭建啊，与遇到些问题

ubuntu建议使用docker
