### ISSUE TITLE
请问web中的secret_key如何设置?

### ISSUE THREAD

**Issue by jwzxgy2007** [jyolo/wLogger#3]
你好，我运行之后访问5000端口被deny，是我哪里设置的不对吗，secret_key应该如何设置?谢谢！

**Comment by jyolo** [comment]
端口在配置中可以自己修改，secret_key 是flask中的配置，一个密钥字符串 你随意设定一个就好

**Comment by jwzxgy2007** [comment]
好的多谢，这里可以了，还有一个问题，我跑起来后显示"Table 'logger.logger_watcher_2020_12_14' doesn't exist"，mysql没有建立数据库是什么原因呢，mysql的用户密码以及logger数据库都建好了，也没有报链接失败的错误
谢谢！

**Comment by jyolo** [comment]
打开 log_debug = True  看看输出的 日志里面情况
