### ISSUE TITLE
页面显示数据异常

### ISSUE THREAD

**Issue by mszhw** [jyolo/wLogger#5]
#### My Question
- [x]  请教一下，我现在遇到的一个问题就是数据库里面已经有数据了，页面也能打开，但就是无法显示数据，get_total_ip以及get_total_pv等在F12里面都是红色的提醒。

#### Environment
- [x] Operating System: Centos 8

#### VMWare IP
- [x] 192.168.31.13

#### Nginx Configuration
-  [x] 192.168.31.13:8080->127.0.0.1:5000

![image](https://user-images.githubusercontent.com/73427261/103120657-ba159900-46b3-11eb-871f-a4dbec8e4b5f.png)

**Comment by jyolo** [comment]
存储引擎是mysql 还是 mongodb? 你直接访问127.0.0.1:5000 呢？ 请求error 信息也截个图看看

**Comment by mszhw** [comment]
#### 存储引擎是: mysql

#### Genel
Request URL: http://127.0.0.1:5000/get_total_ip
Referrer Policy: no-referrer-when-downgrade

#### Request Headers
Provisional headers are shown
Accept: */*
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJsb2NhbC5rcGkuY29tIiwiaWF0IjoxNTkxNjg1OTA1LCJzdWIiOiJ3ZWIiLCJhdWQiOiJBcGFjaGUtSHR0cENsaWVudFwvNC41LjYgKEphdmFcLzEuOC4wXzIwMi1yZWxlYXNlKSIsImV4cCI6MTYyMzIyMTkwNSwidWlkIjo4NCwibmlja25hbWUiOiJ3ZWljb25nIn0.fX1RrO4aOJ-v0QKQ4lSBcjIWyDzzl4F96yDv7_aySHnacUU-4VZbYeec4804-iJBLBmWcM3YheoO-XFqyY9ffdQTjNfobD9WiYPBNJBJAooSQJMOo2H7mwJrXgPTGlFEds1rpXfGHEH2yl7SidPwa4Hq4itR6B1aJOdEY23-8GU
Referer: http://192.168.31.13:8080/
sec-ch-ua: "Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

![image](https://user-images.githubusercontent.com/73427261/103123504-88a2ca80-46bf-11eb-9e48-057c6fe1eff9.png)

![image](https://user-images.githubusercontent.com/73427261/103123525-9a846d80-46bf-11eb-8dcd-2468336d03f1.png)

**Comment by mszhw** [comment]
#### 解决了GET /static/........    304的问题

![image](https://user-images.githubusercontent.com/73427261/103124090-8b9eba80-46c1-11eb-8060-f0869da32d9b.png)

#### 现在的问题依然是F12后台获取ip等信息红色提醒

![image](https://user-images.githubusercontent.com/73427261/103124143-bdb01c80-46c1-11eb-8b97-71e4ade39d36.png)

**Comment by mszhw** [comment]
#### Error

![image](https://user-images.githubusercontent.com/73427261/103129972-b135bf00-46d5-11eb-8192-3d9a0fe84706.png)

**Comment by mszhw** [comment]
### curl http://127.0.0.1:5000/get_total_ip   这样访问也是可以，就是浏览器访问不行

![image](https://user-images.githubusercontent.com/73427261/103130490-d7f4f500-46d7-11eb-8582-e3f04796315f.png)

**Comment by jyolo** [comment]
那就是nginx 反代flask的问题了

**Comment by mszhw** [comment]
需要怎么修改一下呢，能给些建议吗？

**Comment by jyolo** [comment]
我暂时还没试过反代着用因为都是在内网。常规反代不行的换，试试用nginx 的 stream 模块端口转发试试看，改天我有空的话看下这个问题。 感谢反馈~

**Comment by jyolo** [comment]
刚刚更新了一版 ，已解决反代失败的问题 。是flask的server_name 配置导致的反代失败 。配置中新增host 和port ;
请使用host 和 port 代替 server_name
