### ISSUE TITLE
数据库表没有自动创建

### ISSUE THREAD

**Issue by guodonghe** [jyolo/wLogger#8]
数据库表没有自动创建
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'logger.logger_watcher_2020_12_31' doesn't exist")
[SQL: 
                            select count(*) as total_num ,ua from logger_watcher_2020_12_31  
                            where MATCH(`ua`) AGAINST('spider') 
                            GROUP BY ua
                            ORDER BY total_num desc
                              ]
(Background on this error at: http://sqlalche.me/e/13/f405)
![微信图片_20201231145612](https://user-images.githubusercontent.com/20639081/103398597-59d19c00-4b78-11eb-8e9c-2838d384109b.png)

**Comment by jyolo** [comment]
看日志你这是web日志监控模块。
你需要先启动inputer模块 采集日志到队列，再启动outputer 模块将数据解析后存储到数据库中。
当数据库中有数据了，web监控模块才能有数据分析和展现。

**Comment by guodonghe** [comment]
数据库里面的表示启动inputer模块就自动创建，还是启动outputer模块创建，我这3个模块同时启动，还是没看到数据库的表结构及数据

**Comment by jyolo** [comment]
如果你都启动的话，你打开log_debug 看看日志。 如果inputer 用的是tail 模式监控文件，需要有流量进来，outputer 获取到数据才能解析到数据创建表，如果你本地测试建议把  inputer 和 outputer 的 log_debug 看看输出的debug日志 就知道了

**Comment by guodonghe** [comment]
input和output模块日志没有显示报错,web模块有报错，还是现实的上面的内容，我看其他人也有这个问题，另外切割日志目录内没有文件
![微信图片_20201231154025](https://user-images.githubusercontent.com/20639081/103400016-8c7e9300-4b7e-11eb-8ce3-0789854f4856.png)

**Comment by jyolo** [comment]
你把inputer 和 outputer 的日志截图上来看看

**Comment by guodonghe** [comment]
![input](https://user-images.githubusercontent.com/20639081/103403776-534d1f80-4b8c-11eb-8564-f6ae2b65a28f.png)
![output](https://user-images.githubusercontent.com/20639081/103403788-5ea04b00-4b8c-11eb-949f-15caaa999c58.png)

**Comment by guodonghe** [comment]
![nginx日志](https://user-images.githubusercontent.com/20639081/103403857-9c9d6f00-4b8c-11eb-92a0-8e2bae751cee.png)

**Comment by jyolo** [comment]
那你网站都没流量进来啊，肯定就没数据啊

**Comment by jyolo** [comment]
你队列用的是内置的redis 吗？ queue_name  的 配置  inputer 和 outputer 中的是否 一致呢？

**Comment by guodonghe** [comment]
我配置了redis服务，但redis里面没有数据
![Uploading 微信图片_20201231172543.png…]()

**Comment by jyolo** [comment]
那你看看 access.log 日志的权限 是否是可读的？

**Comment by jyolo** [comment]
access.log 日志文件的权限 截个图看看

**Comment by guodonghe** [comment]
权限是可读，我把权限改成777也是一样的

**Comment by jyolo** [comment]
那就奇怪了，刚才我自己又试了下 没问题呀，方便吧 配置文件 截个图看看吧。账号密码 涂掉就好。

**Comment by guodonghe** [comment]
好的，我换个环境再启动下，如果还有问题的话，再麻烦您
