### ISSUE TITLE
ubuntu下inputer开启不了

### ISSUE THREAD

**Issue by zhuozhongcao** [jyolo/wLogger#9]
![image](https://user-images.githubusercontent.com/7440519/103777812-640a0380-506c-11eb-8d47-a071c874080f.png)

outputer和web都已经正常运行

outputer因为收不到数据，一直卡着
web已经可以正常访问，接口正常，就是没有数据

**Comment by zhuozhongcao** [comment]
inputer每次开启之后也没有报错 就直接结束了

**Comment by zhuozhongcao** [comment]
![image](https://user-images.githubusercontent.com/7440519/103778053-ae8b8000-506c-11eb-8600-93ff5b1037f9.png)

**Comment by jyolo** [comment]
inputer 的debug日志截图看看

**Comment by zhuozhongcao** [comment]
你好，已经改好了，我不知道有这个日志文件

最后input那里这么改了
file_path = /var/log/nginx/access.log
log_format_name = defualt

默认的log_format_name = online我这跑不通

**Comment by jyolo** [comment]
嗯 多看下配置详解~  enjoy it ~
